### PR TITLE
Added Animations.py, a file used to provide two animated movements an…

### PR DESCRIPTION
**Pull request by smidtj**
…d users.sql, which contains the information necessary to create the users db and table when creatiung a vm with Vagrant.  Modified .gitignore to include the .vagrant dir (so we don't mess up each others' VMs.). Modified the blank-box-init to utilize the users.sql file in addition to previous worlddb.sql file.  Heavily modified loginscreen.py - implimenting database interacation with psycopg2.  Created welcome message, options to create user and login, and provided functionality to those options. Refactored some functionality as well. Modified main.py to refelct changes in loginscreen.py

### CODE REVIEW

**Comment by CGS-123** [comment]
Dude, overall awesome. When you get some time, just address some of the stuff that I put in there. Feel free to respond with comments back if you feel like what I said was wrong. Definitely looking for discussion over the code. Once all that gets address, lets ship it! :ship:

**Comment by smidtj** [comment]
Hey Guys!

See responses as edits!  Overall I agree with everything suggested.  (Except for the first comment - I'm not sure what it's referencing).  We could probably make most of the suggested edits on the fly here or do another commit? Either way I'm easy =). :+1:

**Comment by CGS-123** [comment]
Hey Jesse, go to commits tab in the middle at the top here and then click on your commit and you will see where my comments are in regards to your code.

**Comment by CGS-123** [comment]
Also, since you've addressed everything, feel free to make the changes in a new commit and then merge the pr. We don't want to slow each other down too much :]

**Comment by CGS-123** [comment]
Looks awesome! Go ahead and merge if everything is good. :ship:

**Pull request merged**
