### PR TITLE
Added manual query functionality

### PR DESCRIPTION
**Pull request by smidtj**
.gitignore - added *.pyc to skip compiled python and deleted all .pyc

blank-box-init - added code to create queries db and tables on vagrant up

myAPP.py - added functions to leaves of query menu

queries.sql - tables for query history/saving

query.py - added ANOTHER overload - enabling the tuple format of executing queries (untested with multiple tuple args)

queryDB.py - code for query menu items (currently set to work within worlddb)

### CODE REVIEW

**Comment by CGS-123** [comment]
:+1:  looks good!

**Comment by cornbreadz** [comment]
Found a bug Line 101 of queryDB.py  if K < i  this block is not inside the for loop where I is declared so variable referenced before assignment.  This happened in the recall queries when i pressed down.  It is only when there are no queries to be recalled.

**Comment by smidtj** [comment]
Oh yea - that would happen if the databases were empty, huh.  I didn't really add any handling for that.  I'll add a quick assignment before entering the loop and a message if the db is empty.

**Comment by cornbreadz** [comment]
Otherwise everything looks fine id say its good to merge.

**Comment by smidtj** [comment]
Alrighty, just made those changes on the fly - take a look and if it's all good, :ship:!

**Comment by cornbreadz** [comment]
Sweet Looks good

**Pull request merged**
